name: Continous Integration
on: 
  push:
    branches: [main]
  workflow_dispatch:
jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1      

    - name:  Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          APP_ECR_REPOSITORY: todo-app
          DB_ECR_REPOSITORY: todo-db
          IMAGE_TAG: latest 

      run: |
        docker build -t $ECR_REGISTRY/$APP_ECR_REPOSITORY:$IMAGE_TAG todo-app/
        docker build -f k8s/Dockerfile.mysql -t $ECR_REGISTRY/$DB_ECR_REPOSITORY:$IMAGE_TAG k8s/
        docker push $ECR_REGISTRY/$APP_ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$DB_ECR_REPOSITORY:$IMAGE_TAG     